# Site
title: 屈定's Blog
subtitle: 屈定's Blog
subtitle_desc: 厌倦需要变化，焦虑需要学习，失落需要价值
keywords: IT小生, Java, Spring, Mybatis, 后端工程师,
description: 日常学习与兴趣交流的个人博客
introduction: 不思量，自难忘！
favicon_ico: /favicon.ico
logo: https://imgblog.mrdear.cn/1518101048.png
qrcode: https://imgblog.mrdear.cn/1588682282.png
default_cover: https://imgblog.mrdear.cn/1514801425.png
header_cover: https://imgblog.mrdear.cn/21312%20%281%29.jpg
error_page_bg: https://imgblog.mrdear.cn/21312%20%281%29.jpg
recommend_img: https://imgblog.mrdear.cn/jikeshijian-jvm.png
author:
  name: 屈定
  link: https://github.com/mrdear
  avatar: https://imgblog.mrdear.cn/avatar.jpg
about:
  info: 编程是一件幸福的事情,不要让你的工作变得索然无味.
  address: HangZhou, China
  email: niudear@foxmail.com

# Me
menu:
  home: /
  archive: /archives/
  works: /works/
  about: /about/

highlight_theme: normal


loader_img: https://imgblog.mrdear.cn/loading.gif

google_site_verification: vI-8_Ee7chpyEu09yCt-bC91dWWmTx08Bb_Mv1gltl0

# Math Equations Render Support
math:
  enable: false

  # Default(true) will load mathjax/katex script on demand
  # That is it only render those page who has 'mathjax: true' in Front Matter.
  # If you set it to false, it will load mathjax/katex srcipt EVERY PAGE.
  per_page: true

  engine: mathjax
  #engine: katex

  # hexo-rendering-pandoc (or hexo-renderer-kramed) needed to full MathJax support.
  mathjax:
    # Use 2.7.1 as default, jsdelivr as default CDN, works everywhere even in China
#    cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    # For newMathJax CDN (cdnjs.cloudflare.com) with fallback to oldMathJax (cdn.mathjax.org).
    #cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    # For direct link to MathJax.js with CloudFlare CDN (cdnjs.cloudflare.com).
    #cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML
    # For automatic detect latest version link to MathJax.js and get from Bootcss.
    #cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

  # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin)
  # needed to full Katex support.
  katex:
    # Use 0.7.1 as default, jsdelivr as default CDN, works everywhere even in China
#    cdn: //cdn.jsdelivr.net/npm/katex@0.7.1/dist/katex.min.css
    # CDNJS, provided by cloudflare, maybe the best CDN, but not works in China
    #cdn: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css
    # Bootcss, works great in China, but not so well in other region
    #cdn: //cdn.bootcss.com/KaTeX/0.7.1/katex.min.css